apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: nextgen-academy
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: hassangill/nextgen-academy-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://localhost:8081/api"
        resources:
          limits:
            cpu: "300m"
            memory: "384Mi"
          requests:
            cpu: "100m"
            memory: "128Mi" 
